### ISSUE TITLE
Urlencode event url slugs

### ISSUE THREAD

**Issue by jonestristand** [vancouverfir/czvr-core#91]
E.g. ? In event name needs to be encoded as %3F as in following url https://czvr.ca/events/Coast-to-coast-ish%3F-2023-11-12%2017:00

**Comment by aabbey33** [comment]
https://github.com/vancouverfir/czvr-core/blob/0172f3ac55c45cbcc50894352812d90f52e1617b/UserEventFetcher/UseEventFetch.py#L114


You can probably add a line here to do a string.replace() and replace any special characters as Hex.


Id probably just create an extra def as encode_websafe(name) and then count any special characters. if a special character is caught, then string replace it with it's hex code and then return the amended complete string at the end of the completed string.

then you can just add a line like 

magic_slug(date, name):
...
store_name = encode_websafe(store_name)
store_name = store_name[:30]
...



Something like that would likely be useful as you wouldn't want to exclusively catch just questionmarks.



It's been some time but this solution *should* still work with displaying human-readable names anyways as magic_slug iirc only creates the URL.

**Comment by jonestristand** [comment]
I thought that would work but based on my test just now we actually need to fix this on the website end since if the 'slug' field in db.events uses %3F, then using that in the URL won't work anymore since the server parses %3F as ? and then compares it to a slug that is now the literal string '?'. I think rather the website should properly urlencode the slug when it reads it from the database and serves the page... There are validated urlencode libs for php that we can use for this..

**Comment by aabbey33** [comment]
Sounds like you've got your solution :)

**Comment by jonestristand** [comment]
Actually I came up with an even easier one. The import script just needs to strip any non-encodeable characters from the slug (mostly just ? and &) :-)

**Comment by aabbey33** [comment]
Yeah that sounds like it'll work great, but you should probably clean up everything after return slugify as we're just returning and then continuing our def anyways

https://github.com/vancouverfir/czvr-core/blob/06e84f430c40be08d0fd8e79fd17b8ddbb7c96c0/UserEventFetcher/UseEventFetch.py#L114C15-L119C15


In fact, you can probably even remove magic_slug,  go back further to Line 93
https://github.com/vancouverfir/czvr-core/blob/06e84f430c40be08d0fd8e79fd17b8ddbb7c96c0/UserEventFetcher/UseEventFetch.py#L93

and change it to

 slug = slugify(i["start] + "-" + i["date"])

**Comment by aabbey33** [comment]
I pushed a fix, myself.

**Comment by jonestristand** [comment]
Bahaha very true, I got too excited and forgot to remove it - thanks!!
